# Generated by Django 5.0.6 on 2024-07-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кузов автомобиля')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузова',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='цвет автомобиля')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Год выпуска',
                'verbose_name_plural': 'Годы выпуска',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название автомобиля')),
                ('image', models.ImageField(upload_to='auto_images/', verbose_name='Изображение автомобиля')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('car_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Body', to='avto.body', verbose_name='Кузов автомобиля')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Color', to='avto.color', verbose_name='цвет автомобиля')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Year', to='avto.year', verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
