# Generated by Django 5.0.6 on 2024-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='публичность'),
        ),
    ]
