# Generated by Django 5.0.6 on 2024-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0002_auto_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(default=' ', help_text='Введите цвет в формате HEX, например #RRGGBB', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.ImageField(upload_to='images\x07uto_images', verbose_name='Изображение автомобиля'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Цвет'),
        ),
    ]
