# Generated by Django 5.0.6 on 2024-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0003_color_color_alter_auto_image_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год выпуска'),
        ),
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.AddField(
            model_name='auto',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-19', verbose_name='дата добавление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images\x07uto_images', verbose_name='Изображение автомобиля'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, verbose_name='цвет автомобиля'),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
