# Generated by Django 5.0.6 on 2024-07-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0004_alter_auto_year_remove_color_color_auto_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение автомобиля'),
        ),
    ]
