# Generated by Django 5.0.6 on 2024-07-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0005_alter_auto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='.images/images', verbose_name='Изображение автомобиля'),
        ),
    ]
