# Generated by Django 5.0.6 on 2024-07-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0008_alter_auto_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='date',
            field=models.DateTimeField(auto_created=True, verbose_name='дата добавление'),
        ),
    ]
